version: "3.7"

services:
  megaqc:
    image: ewels/megaqc
    #build: ..
    volumes:
      # Mount in the startup script
      - ./prestart.sh:/app/prestart.sh
      # Share the static files via a volume
      - static_volume:/app/megaqc/static
      # Add files for testing
      - ./test:/opt/test:ro
    expose:
      - 8000
    depends_on:
      - db
    environment:
      DB_HOST: db
  db:
    image: postgres:latest
    volumes:
      - db_volume:/var/lib/postgresql/data/
      - ./test:/opt/test:ro
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  nginx:
    image: nginx:latest
    volumes:
      # Mount the nginx conf
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount the static files from MegaQC so we can serve them efficiently
      - static_volume:/home/app/web/project/static
    ports:
      - 80:80
    depends_on:
      - megaqc

volumes:
  static_volume:
  db_volume:
