"""empty message

Revision ID: dc45ba7b086d
Revises: 
Create Date: 2019-09-23 18:25:54.379761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc45ba7b086d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_data_type', sa.Column('schema', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample_data_type', 'schema')
    # ### end Alembic commands ###
