"""
empty message.

Revision ID: e38ef2ac89ab
Revises: eb9fdf01bbae
Create Date: 2020-08-05 12:00:54.737816
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e38ef2ac89ab"
down_revision = "eb9fdf01bbae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_dashboard_is_public"), "dashboard", ["is_public"], unique=False
    )
    op.create_index(
        op.f("ix_dashboard_user_id"), "dashboard", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_plot_data_report_id"), "plot_data", ["report_id"], unique=False
    )
    op.create_index(
        op.f("ix_plot_data_sample_id"), "plot_data", ["sample_id"], unique=False
    )
    op.create_index(
        op.f("ix_plot_favourite_user_id"), "plot_favourite", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_report_report_hash"), "report", ["report_hash"], unique=False
    )
    op.create_index(op.f("ix_report_user_id"), "report", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_report_meta_report_id"), "report_meta", ["report_id"], unique=False
    )
    op.create_index(op.f("ix_sample_report_id"), "sample", ["report_id"], unique=False)
    op.create_index(
        op.f("ix_sample_data_report_id"), "sample_data", ["report_id"], unique=False
    )
    op.create_index(
        op.f("ix_sample_data_sample_id"), "sample_data", ["sample_id"], unique=False
    )
    op.create_index(
        op.f("ix_sample_filter_is_public"), "sample_filter", ["is_public"], unique=False
    )
    op.create_index(
        op.f("ix_sample_filter_user_id"), "sample_filter", ["user_id"], unique=False
    )
    op.create_index(op.f("ix_uploads_status"), "uploads", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_uploads_status"), table_name="uploads")
    op.drop_index(op.f("ix_sample_filter_user_id"), table_name="sample_filter")
    op.drop_index(op.f("ix_sample_filter_is_public"), table_name="sample_filter")
    op.drop_index(op.f("ix_sample_data_sample_id"), table_name="sample_data")
    op.drop_index(op.f("ix_sample_data_report_id"), table_name="sample_data")
    op.drop_index(op.f("ix_sample_report_id"), table_name="sample")
    op.drop_index(op.f("ix_report_meta_report_id"), table_name="report_meta")
    op.drop_index(op.f("ix_report_user_id"), table_name="report")
    op.drop_index(op.f("ix_report_report_hash"), table_name="report")
    op.drop_index(op.f("ix_plot_favourite_user_id"), table_name="plot_favourite")
    op.drop_index(op.f("ix_plot_data_sample_id"), table_name="plot_data")
    op.drop_index(op.f("ix_plot_data_report_id"), table_name="plot_data")
    op.drop_index(op.f("ix_dashboard_user_id"), table_name="dashboard")
    op.drop_index(op.f("ix_dashboard_is_public"), table_name="dashboard")
    # ### end Alembic commands ###
