name: Python tests and Node.js build

on: [push, pull_request]

jobs:
  build-python:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2.1.4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: snok/install-poetry@v1.3.4

      - name: Install all extra features of poetry
        run: poetry install --extras "dev"

      - name: Test with pytest
        run: poetry run pytest

  build-node:
    env:
      # Webpack uses around 2GB to build, which is more than the default heap size. We bump it to 4 GB here just in case
      NODE_OPTIONS: "--max-old-space-size=4096"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Test build
        run: npm run build
