name: Publish documentation

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v2
        name: Check out source-code repository

      - name: Setup Python
        uses: actions/setup-python@v3.1.1
        with:
          python-version: 3.9

      - name: Install pip
        run: python -m pip install --upgrade pip

      # Required to automatically extract Click CLI and Flask API documentation
      - name: Install MegaQC
        run: pip install -e .[dev]

      - name: Install documentation dependencies
        run: pip install -r docs/requirements.txt

      - name: Create API documentation
        run: |
          cd docs
          make api-docs

      - name: Build documentation
        run: |
          cd docs
          make html
          echo "megaqc.info" > _build/html/CNAME

      # TODO: We could also build latex & PDF documentation and upload them as artifacts

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
